### ISSUE TITLE
Why it can not parse (div span a{color: #789}) into tree nodes?

### ISSUE THREAD

**Issue by jackiewillen** [NV/CSSOM#101]
For Example.When i have a css like this.
div span a {color: #789};
It need to build a cssom like this  body ->div->span->a  with four nodes。as below:
{
    parentNode: body,
    children: {
          parentNode: div,
          children: {
                parentNode: span,
                children: {
                     node: a
                 }
          }
   }
}

Why the CSSOM just generate one object property like below?

{     parentStyleSheet: null,     
      cssRules: [         
                  {             
                       parentRule: null,             
                       parentStyleSheet: "../..",             
                       selectorText: "div span a",            
                       style: {                 
                            0: "color",                 
                            length: 1,                
                            parentRule: "..",                 
                           _importants: {                     color: ""                 },                
                           __starts: 7,                 
                          color: "#789"             },             __starts: ,             __ends: 20         }     ] }

**Comment by NV** [comment]
That's not how CSSOM works. The current output is correct.
