### ISSUE TITLE
CSSMediaRule should derive from CSSConditionRule

### ISSUE THREAD

**Issue by TimothyGu** [NV/CSSOM#105]
In the latest [spec](https://drafts.csswg.org/css-conditional-3/#cssmediarule), CSSMediaRule now derives from CSSConditionRule, which derives from CSSGroupingRule. Some methods that are useful that are now available for CSSMediaRule include [`insertRule()`](https://drafts.csswg.org/cssom-1/#dom-cssgroupingrule-insertrule), which is requested by @jspurlin in https://github.com/jsdom/jsdom/issues/2974.

**Comment by NV** [comment]
CSSOM isn't actively maintained. That being said, I still take pull requests.
