### ISSUE TITLE
TypeError: Object#<Object> has no method 'existsSync'

### ISSUE THREAD

**Issue by ghost** [NV/CSSOM#66]
Hi, wanted to try CSSOM but unfortunately i got:

TypeError: Object#<Object> has no method 'existsSync'

when I ran: ./node_modules/.bin/jake

What I am doing wrong?
System is: Ubuntu 12.04
npm -v: 1.1.4
node -v: v0.6.12

Thanks

**Comment by domenic** [comment]
You need a newer Node version.
