### ISSUE TITLE
W3C "transform" style doesn't work

### ISSUE THREAD

**Issue by yaycmyk** [NV/CSSOM#78]
To replicate, create an element and do the following with it:

```js
const domElement = document.createElement('div');

domElement.style.transform = 'translate3d(0px, 0px, 0px)';

assert(domElement.style.transform === 'translate3d(0px, 0px, 0px)'); // undefined
```

I can only get it to work if I use this specific pattern:

```js
const domElement = document.createElement('div');

domElement.style['webkit-transform'] = 'translate3d(0px, 0px, 0px)';

assert(domElement.style.WebkitTransform === 'translate3d(0px, 0px, 0px)');
```

X-issue from https://github.com/tmpvar/jsdom/issues/1321

**Comment by domenic** [comment]
For the record I can merge PRs and publish CSSOM so if you pull request a fix it should show up in jsdom pretty quickly :)

**Comment by yaycmyk** [comment]
Alright, perhaps I will take a crack at this tomorrow :)

**Comment by yaycmyk** [comment]
Closing this - the issue is actually in https://github.com/chad3814/CSSStyleDeclaration

**Comment by ArsSirek** [comment]
Hi all,
My case isn't exactly same, but it seems very related
``` javascript
const jsdom = require("jsdom");
const {JSDOM} = jsdom;
const dom = new JSDOM('<div id="test" style="transform: translate(0,-50%); font-size:10px;"></div>', {
    runScripts: "outside-only",
});
var target = dom.window.document.getElementById('test');
target.style.fontWeight = 'bold';
console.log(dom.serialize());
```
when there is no action with styles, than inline styles preserved as they were in original html,
however in the example above the console output is
``` html
<html><head></head><body><div id="test" style="font-size: 10px; font-weight: bold;"></div></body></html>
```
font-size style are preserved fine, but not the transform style.
I can see via debugger that target.style treat transform differently
``` json
{
  "0": "font-size",
  "_values": {
    "font-size": "10px"
  },
  "_importants": {
    "transform": "",
    "font-size": ""
  },
  "_length": 1,
  "transform": "translate(0,-50%)"
}
```
But i wasn't able to find were the related code is in the projects, nor to come up with temp fix.. 
@domenic will merging the chad3814/CSSStyleDeclaration#49 resolve this as well? if not, can you please advise me what can be done?
