### ISSUE TITLE
Wrong type for CSSKeyframesRule and CSSKeyframeRule

### ISSUE THREAD

**Issue by artf** [NV/CSSOM#95]
**CSSOM Code**
[CSSKeyframesRule = 8](https://github.com/NV/CSSOM/blob/master/lib/CSSKeyframesRule.js#L20)
[CSSKeyframeRule = 9](https://github.com/NV/CSSOM/blob/master/lib/CSSKeyframeRule.js#L22)

[**Specs**](https://www.w3.org/TR/css-animations-1/#interface-cssrule-idl)
CSSKeyframesRule = 7
CSSKeyframeRule = 8

**Comment by NV** [comment]
Fixed in 7b0d9aaf2dd8ab9fb0a5c9177539fdf01e06291f. Thank you!

Published in [v0.4.0](https://www.npmjs.com/package/cssom/v/0.4.0).
